server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://micro-sql.local:3308/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://configserver:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka

info:
  app:
    name: "cards"
    description: "StBank Cards Microservice"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
    prometheus:
      access: unrestricted
  prometheus:
   metrics:
     export:
       enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      stpunk47:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"