services:
  accounts:
    image: stpunk47/accounts:v2
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "512m"
    networks:
      - stbank-network
  loans:
    image: stpunk47/loans:v2
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "768m"  # Increased from 512m to 768m
    networks:
      - stbank-network
  cards:
    image: stpunk47/cards:v2
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "512m"
    networks:
      - stbank-network
networks:
  stbank-network:
    driver: "bridge"