spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://configserver:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: redis.local
      port: 6379
      timeout: 1s

info:
  app:
    name: "gatewayserver"
    description: "StBank Gateway Server"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
    gateway:
      access: unrestricted
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
       enabled: true

logging:
  level:
    com:
      stpunk47:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s