server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://micro-sql.local:3307/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://configserver:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka

info:
  app:
    name: "loans"
    description: "StBank Loans Microservice"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted

logging:
  level:
    com:
      stpunk47:
        loans: DEBUG