spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://configserver:8071/"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
