server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://micro-sql.local:3306/accountsdb
    username: root
    password: root
  sql:
   init:
    mode: always

  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka

info:
  app:
    name: "accounts"
    description: "StBank Accounts Microservice"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted