spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Hello from the PROD accounts service"
  contactDetails:
    name: "John Doe - Product Manager"
    email: "customer@hostname.com"
  onCallSupport:
    - (111) 555-5555
    - (111) 555-5556