spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Hello from the QA accounts service"
  contactDetails:
    name: "John Doe - QA"
    email: "customer@hostname.com"
  onCallSupport:
    - (666) 555-5555
    - (666) 555-5556